<h1> IMDB sentiment classification</h1>

In [17]:
from keras.datasets import imdb

In [35]:
(train_x,label_train),(test_x,label_test)=imdb.load_data(num_words=5000)

In [36]:
for sample in range(3):
    print(train_x[sample])

[1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 2, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 2, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 2, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 2, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 2, 19, 178, 32]
[1, 194, 1153, 194, 2, 78, 228, 5, 6, 1463, 4369, 2, 134, 26, 4, 715, 8, 11

In [37]:
for y in range(3):
    print(label_train[y])

1
0
0


check the dictionionary size

In [38]:
max([max(sequence) for sequence in train_x])

4999

In [39]:
train_x.shape

(25000,)

In [40]:
test_x.shape

(25000,)

reversing the indexes to their respective words

In [41]:
word_index=imdb.get_word_index()
reversed_index=dict([(value,key) for (key,value) in word_index.items()])
decoded_review=' '.join([reversed_index.get(i-3,'?') for i in train_x[0]])
decoded_review2=' '.join([reversed_index.get(i-3,'?') for i in test_x[0]])

In [42]:
decoded_review2

"? please give this one a miss br br ? ? and the rest of the cast ? terrible performances the show is flat flat flat br br i don't know how michael ? could have allowed this one on his ? he almost seemed to know this wasn't going to work out and his performance was quite ? so all you ? fans give this a miss"

In [28]:
decoded_review

"? this film was just brilliant casting location scenery story direction everyone's really suited the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same scottish island as myself so i loved the fact there was a real connection with this film the witty remarks throughout the film were great it was just brilliant so much that i bought the film as soon as it was released for ? and would recommend it to everyone to watch and the fly ? was amazing really cried at the end it was so sad and you know what they say if you cry at a film it must have been good and this definitely was also ? to the two little ? that played the ? of norman and paul they were just brilliant children are often left out of the ? list i think because the stars that play them all grown up are such a big ? for the whole film but these children are amazing and should be ? for what they have done don't you think the whole story wa

one hot encoding the data

In [43]:
import numpy as np
train_f=np.zeros((len(train_x),5000))
for i,train_x in enumerate(train_x):
    train_f[i,train_x]=1
print(train_f[0])

[0. 1. 1. ... 0. 0. 0.]


In [44]:
train_f[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [45]:
test_f=np.zeros((len(test_x),5000))
for i,test_x in enumerate(test_x):
    test_f[i,test_x]=1
print(test_f[0])

[0. 1. 1. ... 0. 0. 0.]


In [46]:
test_f.shape

(25000, 5000)

In [47]:
train_f.shape

(25000, 5000)

vectorizing the labels

In [48]:
label_train=np.asarray(label_train).astype('float32')
label_test=np.asarray(label_test).astype('float32')

In [49]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import rmsprop

In [50]:
model=Sequential()
model.add(Dense(16,activation='relu',input_shape=(5000,)))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 16)                80016     
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 136       
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 80,161
Trainable params: 80,161
Non-trainable params: 0
_________________________________________________________________


In [51]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])

In [52]:
result=model.fit(train_f,label_train,epochs=30,batch_size=200)

Epoch 1/30
25000/25000 [==============================] - 6s 231us/step - loss: 0.3937 - acc: 0.8424
Epoch 2/30
25000/25000 [==============================] - 3s 105us/step - loss: 0.2468 - acc: 0.9036
Epoch 3/30
25000/25000 [==============================] - 3s 108us/step - loss: 0.2128 - acc: 0.9179
Epoch 4/30
25000/25000 [==============================] - 3s 102us/step - loss: 0.1952 - acc: 0.9267
Epoch 5/30
25000/25000 [==============================] - 3s 104us/step - loss: 0.1816 - acc: 0.9321
Epoch 6/30
25000/25000 [==============================] - 3s 106us/step - loss: 0.1709 - acc: 0.9356
Epoch 7/30
25000/25000 [==============================] - 3s 102us/step - loss: 0.1583 - acc: 0.9405
Epoch 8/30
25000/25000 [==============================] - 3s 102us/step - loss: 0.1477 - acc: 0.9445
Epoch 9/30
25000/25000 [==============================] - 3s 103us/step - loss: 0.1365 - acc: 0.9491
Epoch 10/30
25000/25000 [==============================] - 3s 102us/step - loss: 0.1240 - a

In [53]:
loss,accuracy=model.evaluate(test_f,label_test)

25000/25000 [==============================] - 3s 115us/step


In [54]:
print('loss is:',loss,'and accuracy is :',accuracy)

loss is: 1.346697738431096 and accuracy is : 0.84268


thus we have achieved 84.26% accuracy

In [55]:
model.save('imdb_review.h5')